config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]

  root to: 'pages#home'
  # path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :brains do
    resources :reviews, only: [:create]
    resources :bookings, only: [:create, :new, :show]
  end

  resources :bookings, only: [:index, :delete] do
    member do
      patch "accept"
      patch "reject"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :brain
  enum status: [:pending, :accepted, :rejected] # accessing with index
end

app/models/brain.rb
class Brain < ApplicationRecord
  validates :name, :category, :eq, :iq, :price_per_minute, presence: true
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  before_create :set_icon_path
  CATEGORY = ["Heros", "Sports", "Science", "Philosophy", "EvilMinds", "Saviours", "Arts", "T.A's"]

  def set_icon_path
    @icon_path = "brain_icons/Brain_icon_#{(1..9).to_a.sample}"
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :brain
  validates :comment, :rating, presence: true
  validates :rating, numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  #before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #:omniauthable

  # validates :fullname, length: { maximum: 40 }, presence: true
  # validates :password, length: { maximum: 8 }, presence: true
  has_many :brains
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    brains_path(current_user) # your path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  require "date"

  def index
    @outgoing_bookings = Booking.where(user: current_user) # bookings i made
    if current_user.brains.any? # checking if user is host of brains
      @my_brains = current_user.brains # returns collection of brains
      @incoming_bookings = Booking.where(brain_id: @my_brains.pluck(:id))
    end
  end

  def new
    # we need @brain in our `simple_form_for`
    @brain = Brain.find(params[:brain_id])
    @booking = Booking.new
  end

  def calculate_total
    @first_date = Date.new(params[:booking]["start_date(1i)"].to_i, params[:booking]["start_date(2i)"].to_i, params[:booking]["start_date(3i)"].to_i)
    @second_date = Date.new(params[:booking]["end_date(1i)"].to_i, params[:booking]["end_date(2i)"].to_i, params[:booking]["end_date(3i)"].to_i)
    @total_of_days = (@second_date - @first_date).to_i
    @total = @total_of_days * @brain.price_per_minute * 1440
  end

  def create
    @booking = Booking.new(booking_params)
    # we need `brain_id` to associate review with corresponding restaurant
    @brain = Brain.find(params[:brain_id])
    @booking.brain = @brain
    @booking.user = current_user
    @booking.total = calculate_total
    @booking.start_date = @first_date
    @booking.end_date = @second_date
    @booking.availability = false
    @booking.save
    @booking.pending = true
    redirect_to bookings_path
  end

  def show
    @booking = Booking.find(params[:id])
    @booking = Booking.new
    @brain = Brain.find(params[:brain_id])
    @booking.user = current_user
    @booking.brain = @brain

  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.accepted!
    @booking.pending = false
    @booking.status = 1
    redirect_to bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.rejected!
    @booking.pending = false
    @booking.status = 2
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:content, :current_user, :brain_id, :start_date, :end_date, :price, :total)
  end
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  def index
    @brains = Brain.all
    # the `geocoded` scope filters only brains with coordinates (latitude & longitude)
    @markers = @brains.geocoded.map do |brain|
      {
        lat: brain.latitude,
        lng: brain.longitude,
        info_window: render_to_string(partial: "info_window", locals: { brain: brain }),
        image_url: helpers.asset_url('brain_logo_emoji.png')
      }
    end
    if params[:query].present?
      @brains = Brain.where(category: params[:query])
    else
      @brains = Brain.all
    end
  end

  def show
    @brain = Brain.find(params[:id])
  end

  def new
    @brain = Brain.new
  end

  def edit
  end

  # POST /brains
  def create
    @brain = Brain.new(brain_params)
    @brain.icon_path = @brain.set_icon_path
    # @brain.user = current_user
    @brain.user = current_user

    if @brain.save
      redirect_to @brain, notice: 'Brain was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /brains/1
  def update
    if @brain.update(brain_params)
      redirect_to @brain, notice: 'Brain was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /brains/1
  def destroy
    @brain.destroy
    redirect_to brains_path, notice: 'Brain was successfully destroyed.'
  end

  private

  def set_brain
    @brain = Brain.find(params[:id])
  end

  def brain_params
    params.require(:brain).permit(:name, :category, :description, :address, :eq, :iq, :price_per_minute)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%= render "shared/navbar" %>


<div class="container">
  <div class="row">
    <div class="col-12 d-flex align-items-end flex-column">
      <h1 class="mr-auto mt-5 mb-5" style="color:black">Hey <% if current_user %>
<%= current_user.fullname %><%end%>, <br>here are all your bookings 🧠 🧠 🧠</h1>
    </div>
  </div>
</div>

<div class="container">
 <h1 style="color:black" class="mb-5 mt-3">My Bookings</h1>
  <div class="row animated fadeInUp">
      <% @outgoing_bookings.each do |booking|  %>
          <div class="col-3 p-4 mb-5" id="genius_card" >
          <%= image_tag "#{booking.brain.icon_path}.png", alt: "Le Wagon", width: 90 %>
          <h5 class="pl-1 mt-5"><%= booking.brain.name %> </h5>
            <h5 class="pl-1 mt-5 mb-4">Your Total<br> <%= booking.total %> ₿</h5>
            <h5 class="pl-1 mb-4"> <%= image_tag "shuttle.png", alt: "Start", width: 20 %>&nbsp; &nbsp; <%= booking.start_date.strftime("%B %d") %></h5>
             <h5 class="pl-1"> <%= image_tag "end.png", alt: "Start", width: 20 %>&nbsp; &nbsp; <%= booking.end_date.strftime("%B %d") %></h5>

        </div>
        <div class="col-1"></div>
      <% end %>
  </div>
</div>





<!--
<div class="container">
  <div class="row">
     <h3>outgoing bookings</h3>
      <%# @outgoing_bookings.each do |booking|  %>
        <div class="col-3"  id="genius_card" >
          <%#= image_tag "brain_icon_passive", alt: "Le Wagon", width: 200 %>
            <div class="space_flex mb-3">
              <h5 class="pl-1">Your total is <%#= booking.total %> ₿</h5>
              <h5 class="pl-1 ">Start Date:<%#= booking.start_date %></h5>
              <h5 class="pl-1 ">End Date:<%#= booking.end_date %></h5>
            </div>
        </div>
      <%# end %>
  </div>
</div>

<div class="container mt-5 mb-5">
  <div class="row">
    <h3>outgoing bookings</h3>
    <%# @outgoing_bookings.each do |booking|  %>
  <%#= link_to brain_booking_path(booking.brain, booking) do %>
      <div class="col-3 p-4 mb-5"  id="genius_card" >
        <%#= image_tag "brain_icon_passive", alt: "Le Wagon", width: 200 %>
          <div class="space_flex mb-3">
            <h5 class="pl-1">Your total is <%#= booking.total %> ₿</h5>
            <h5 class="pl-1 ">Start Date:<%#= booking.start_date %></h5>
            <h5 class="pl-1 ">End Date:<%#= booking.end_date %></h5>
            <h5 class="pl-1 ">
              <%# if booking.pending?%>
                <h5>Your booking request is currently being processed.</h5>
                <%# else %>
                <h5>Your booking got <%#= booking.status %>!</h5>
              <%# end %>
          </div>
      </div>

      <div class="col-1"></div>
      </div>
    <%# end %>
    <%# end %>
  </div>
</div>

<div class="container mt-5 mb-5">



  <div class="row">

    <h3>incoming bookings</h3>
    <%# @incoming_bookings.each do |booking|  %>
      <%# if booking.pending %>

        <div class="col-3 p-4 mb-5"  id="genius_card" >
          <%#= image_tag "brain_icon_passive", alt: "Le Wagon", width: 200 %>
          <div class="space_flex mb-3">
            <h5 class="pl-1">The total is <%#= booking.total %> ₿</h5>

            <h5 class="pl-1 ">Start Date:<%#= booking.start_date %></h5>

            <h5 class="pl-1 ">End Date:<%#= booking.end_date %></h5>

          </div>
          <div class="space_flex mb-3">
            <%#= link_to "(accept ✅)", accept_booking_path(booking), method: :patch %>
            <%#= link_to "(reject ❌)", reject_booking_path(booking), method: :patch %> <%#= by default link is get request, need to make this patch %>
          </div>
        </div>

      <%# else %>
        <div class="col-3 p-4 mb-5"  id="genius_card" >
          <%#= image_tag "brain_icon_passive", alt: "Le Wagon", width: 200 %>
          <div class="space_flex mb-3">
            <h5 class="pl-1">Your confirmed booking will take place:</h5>
            <h5 class="pl-1 ">Start Date:<%#= booking.start_date %></h5>
            <h5 class="pl-1 ">End Date:<%#= booking.end_date %></h5>
          </div>
        </div>
      <%# end %>

      <div class="col-1"></div>
      </div>
    <%# end %>
  </div>
 -->

app/views/bookings/new.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <div class="row mt-5">
    <div class="col-12">
    <h1 class="mt-5 mb-5" style="color:black">Book your Brain</h1>
    <%= simple_form_for [ @brain, @booking ] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Book this brain", class: "btn btn-primary mt-3", data: { confirm: 'Are you sure you want to book this brain?' } %>


<% end %>
</div>
  </div>
</div>

app/views/bookings/show.html.erb
<%= render "shared/navbar" %>
<h2>Bookings</h2>
</div>
  <div class="space_flex mb-3">
      <%= link_to "(accept ✅)", accept_booking_path(@booking), method: :patch %>
      <%= link_to "(reject ❌)", reject_booking_path(@booking), method: :patch %> <%#= by default link is get request, need to make this patch %>
  </div>
</div>

app/views/brains/_form.html.erb
</div class="container">

  <div class="row">
    </div class="col-12">
      <%= simple_form_for(@brain) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :category, :collection => %w[Phylosophy, Sports, Hero] %>
  </div>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.input :address %>
  </div>

  <div class="form-inputs">
    <%= f.input :price_per_minute %>
  </div>

  <div class="form-inputs">
    <%= f.input :iq %>
  </div>

  <div class="form-inputs">
    <%= f.input :eq %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

    </div>
  </div>

</div>

app/views/brains/_info_window.html.erb
<h2><%= brain.name %></h2>
<p><%= brain.address %></p>

app/views/brains/edit.html.erb
<%= render "shared/navbar" %>

<div class="container">
  <div class="row">

    <div class="col-12">
      <h1 class="mt-5 mb-5" style="color:black">Editing Brain</h1>
    <%= simple_form_for(@brain) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.input :price_per_minute %>
  </div>

  <div class="form-inputs">
    <%= f.input :iq %>
  </div>

  <div class="form-inputs">
    <%= f.input :eq %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mt-3 mb-3" %>
  </div>
<% end %>

      <%= link_to 'Back to all brains', brains_path %>

    </div>

  </div>

</div>

app/views/brains/index.html.erb
<%= render "shared/navbar" %>

<div class="container">
  <div class="row">
    <div class="col-12 d-flex">
      <h1 class="mr-auto mt-5 mb-5" style="color:black">Hey <% if current_user %>
        <%= current_user.fullname %>
        <% end %>, check out <br> those juicy brains 🧠 🧠 🧠</h1>
    </div>
  </div>

  <div class="animated fadeInUp" id="map"
    style="width: 100%; height: 600px; border-radius: 10px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

</div>

<div class="container mt-5 mb-5 animated fadeInUp">

  <div class="row">

    <div class="col-12 mb-5">

<div class="d-flex bd-highlight align-items-center">

  <div class="mr-auto p-2 bd-highlight"><%= link_to "Create a new Brain", new_brain_path %></div>
   <div class="p-2 bd-highlight mr-5"> <%= form_tag brains_path, method: :get do %>
      <%= select_tag(:query, options_for_select(Brain::CATEGORY, params[:query]))  %>
      <%= submit_tag "Select", class: "btn btn-link" %>
    <% end %>
  </div>
</div>
    </div>
  </div>

  <div class="row animated fadeInUp">
    <% @brains.each do |brain|  %>
      <%= link_to brain_path(brain) do %>
        <div class="col-3 p-4 mb-5" id="genius_card" >
          <%= image_tag "#{brain.icon_path}.png", alt: "Le Wagon", width: 90 %>
          <h5 class="text-start pl-1 mt-5 mb-2"><%= link_to brain.name, brain_path(brain) %></h5>
        <div class="space_flex mb-3">
          <h5 class="pl-1"><%= brain.price_per_minute %> ₿</h5>
          <h5 class="pl-1 "><%= brain.iq %> IQ</h5>
        </div>
      <% end %>
      </div>
      <div class="col-1"></div>
    <% end %>
    </div>
  </div>


</div>

app/views/brains/new.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <div class="row">
    <div class="col-12 mt-5">
      <h1 class="mb-5" style="color:black">Create a new brain</h1>
      <%= simple_form_for @brain do |f| %>
        <%= f.input :name %>
        <%= f.input :category, :collection => %w[Heros Sports Science Philosophy EvilMinds Saviours Arts T.A's] %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :price_per_minute %>
        <%= f.input :iq %>
        <%= f.input :eq %>
        <%= f.submit class: 'btn btn-primary mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/brains/show.html.erb
<div class="container mb-5">
<%= render "shared/navbar" %>
</div>

<div class="container mb-5 mt-5">
  <div class="row animated fadeInLeft">
<div class="col-12">
<h2>Check out this juicy Brain of:</h2>
<h1 class="display-1 mt-5 mb-5" style="color:black"><%= @brain.name %></h1>
<%= bar_chart iq: @brain.iq, Ø: 98, eq: @brain.eq %>
 </div>
  </div>

  <p id="notice"><%= notice %></p>

<div class="container mt-5">
<div class="row animated fadeInLeft">
  <div class="col-12">
    <div class="d-flex align-items-center ">
      <h3 class="mr-auto">
        <strong>Price:</strong>
        <%= @brain.price_per_minute %> ₿
      </h3>
      <h4><%= link_to 'Book this brain', new_brain_booking_path(@brain) %></h4>
    </div>

<h2 class="mt-5"><strong>Description</strong></h2>

<h2 class="mt-2 mb-5">
  <%= @brain.description %>
</h2>

<%= link_to 'Back', brains_path %> |


<%= link_to 'Edit', edit_brain_path(@brain) %> |






<%= link_to 'Delete this brain', brain_path(@brain), method: :delete,  data: { confirm: 'Are you sure you want to delete this brain?' }  %>

</div>
</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= stylesheet_pack_tag 'application' %>

    <title>RentABrain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
   <%= render "shared/navbar_home" %>
 <canvas class="bg" width='1000px' height='1200px'></canvas>

<div class="wrapper">
  <div class="container">
  <div class="row">
  <div class="col-12">
           <h1 class="display-2" style="font-weight: 500;border-bottom: 2px solid white">Rent Your Brain</h1>
          <h5 class="" style="line-height:30px; color:white">
          Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
          </h5>
          <button type="button" class="btn btn-primary btn-lg mt-5">Join</button>
  </div>
  </div>
  </div>
  </div>

    </div>


</div>

app/views/shared/_navbar.html.erb
<div class="container">
<div class="navbar mt-3 navbar-expand-sm navbar-light navbar-lewagon" position="relative:z-index: 99">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "Brain_logo_black.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
             <%= link_to "Home", root_path, class: "nav-link pr-4 pl-3 " %>
        </li>
        <li class="nav-item">
          <%= link_to "Brains", brains_path, class: "nav-link pr-4 pl-3" %>
        </li>
        <li class="nav-item dropdown mr-5">
          <%= image_tag "george.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="container">
<div class="navbar mt-3 navbar-expand-sm navbar-light navbar-lewagon" position="relative:z-index: 99">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "Brain_logo_white.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link pr-4 pl-3 homeboy", id: "homelink", html: {color: "white"} %>

        </li>
        <li class="nav-item">
          <%= link_to "Brains", brains_path, class: "nav-link pr-4 pl-3" , id: "homelink" %>
        </li>
        <li class="nav-item dropdown mr-5">
          <%= image_tag "donald.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", id: "homelink" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>